"""Assemble VALIDATION.md from training/runs/*.json and tests/out/results.json."""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
R = lambda p: json.load(open(os.path.join(HERE, "runs", p)))


def f(x, n=4):
    return f"{x:.{n}f}"


def main():
    variants = R("variants.json")
    onnx = R("onnx_check.json")
    comp = R("model_comparison.json")
    final = R("final_eval.json")
    ft = R("finetune_log.json")
    res = json.load(open(os.path.join(ROOT, "tests", "out", "results.json")))
    cfg = json.load(open(os.path.join(ROOT, "web", "config.json")))
    shipped = cfg["model"]["id"]
    L = []
    w = L.append
    w("# Validation\n")
    w(f"Shipped model: `{shipped}` (`{cfg['model']['file']}`, {onnx['onnx_bytes']/1e6:.1f} MB fp32). "
      f"Preprocessing: aligned 350x350 crop, resize 256, center crop 224, ImageNet normalization, RGB.\n")
    w("All numbers are regenerated by `training/write_validation.py` from `training/runs/*.json` "
      "and `tests/out/results.json`.\n")

    w("## Summary\n")
    w("| Check | Result | Target | Pass |\n|---|---|---|---|")
    w(f"| Test Pearson, shipped model, Python, full 2200 test images | {f(final['all']['pearson'])} | >= 0.85 | {'yes' if final['all']['pearson'] >= 0.85 else 'NO'} |")
    e = res["e2e"]
    same = e["pearson_python_same_images"]
    w(f"| End to end Pearson, browser pipeline, 300 test images | {f(e['pearson_js'])} | within 0.03 of Python ({f(same)} on the same 300; {f(final['all']['pearson'])} on all 2200) | {'yes' if abs(e['pearson_js'] - final['all']['pearson']) <= 0.03 else 'NO'} |")
    d = res["determinism"]
    w(f"| Determinism, same image 20 times (+1 fresh browser context) | {d['unique_outputs']} unique output, bits 0x{d['float32_bits_hex']} | bit identical | {'yes' if d['bit_identical'] else 'NO'} |")
    w(f"| ONNX Runtime (Python) vs PyTorch, 200 images | max abs diff {onnx['max_abs_diff']:.2e} | < 0.005 | {'yes' if onnx['pass'] else 'NO'} |")
    q = res["quality"]
    w(f"| Quality gates (rotated, turned, smiling, two faces, small, dark, no face, EXIF) | {sum(v['pass'] for v in q.values())}/{len(q)} as expected | all | {'yes' if all(v['pass'] for v in q.values()) else 'NO'} |")
    m = res["mobile"]
    w(f"| Mobile layout 390x844 | scrollWidth {m['scrollWidth']}, {len(m['offenders'])} overflowing elements | no overflow | {'yes' if not m['overflow'] else 'NO'} |")
    w(f"| Offline after first load (service worker) | app ready offline: {res.get('offline', {}).get('app_ready_offline')} | works | {'yes' if res.get('offline', {}).get('app_ready_offline') else 'NO'} |")
    w("")

    w("## Phase 1: model\n")
    w("### Pretrained weights (Gustrd/SCUT-FBP5500-PyTorch-Model, resnet18_py3.pth), preprocessing variants on the TEST split\n")
    w("Unaligned SCUT images, Pillow bilinear resize.\n")
    w("| Resize | Normalization | Channels | Pearson | MAE | RMSE |\n|---|---|---|---|---|---|")
    for v in variants["test"]:
        w(f"| {v['resize']} | {v['norm']} | {v['channels']} | {f(v['pearson'])} | {f(v['mae'])} | {f(v['rmse'])} |")
    bt = variants["best_on_train"]
    w(f"\nBest variant on the TRAIN split: Pearson {f(bt['pearson'])}, MAE {f(bt['mae'])} "
      f"(TEST: {f(variants['test'][0]['pearson'])}, {f(variants['test'][0]['mae'])}).\n")

    w("### Pretrained vs fine tuned, through the app preprocessing (aligned crops)\n")
    w("| Model | Train Pearson | Test Pearson | Test MAE | Test RMSE | Train minus test Pearson |\n|---|---|---|---|---|---|")
    tta = R("tta_check.json")
    for k, v in comp.items():
        w(f"| {k} | {f(v['train_aligned']['pearson'])} | {f(v['test_aligned']['pearson'])} | {f(v['test_aligned']['mae'])} | {f(v['test_aligned']['rmse'])} | {f(v['gap_pearson'])} |")
    for k, v in tta.items():
        t = v["flip_avg"]
        w(f"| {k} + flip average{' (**shipped**)' if k == 'finetuned' else ''} | | {f(t['pearson'])} | {f(t['mae'])} | {f(t['rmse'])} | |")
    w(f"\nFlip average = mean of the prediction for the crop and for its mirror image, baked into the ONNX graph. "
      f"Without it, mirroring a photo changes the fine tuned model's score by {tta['finetuned']['flip_mean_abs_disagreement']:.3f} on average.")
    w("\nThe fine tuned model was trained on the train split only, so its test number is a clean held out "
      "measurement. The pretrained model shows almost no train/test gap, which suggests these weights were not "
      "trained on exactly this train split (see DECISIONS.md, decision 8), so its test number may be optimistic.\n")
    w(f"Fine tuning: {ft['epochs']} epochs, batch {ft['batch']}, {ft['history'][-1]['elapsed_min']:.0f} minutes on 4 CPU cores "
      "(including building the aligned crops). Per epoch test Pearson (for information only, never used to pick a checkpoint): "
      + ", ".join(f(h['test']['pearson'], 3) for h in ft["history"]) + ".\n")

    w("### Shipped model on the full TEST split (Python, app preprocessing)\n")
    w("| Subset | n | Pearson | MAE | RMSE |\n|---|---|---|---|---|")
    for k in ("all", "gender=Male", "gender=Female", "race=Asian", "race=Caucasian", "smile<=0.5", "smile>0.5"):
        v = final[k]
        w(f"| {k} | {v['n']} | {f(v['pearson'])} | {f(v['mae'])} | {f(v['rmse'])} |")
    w(f"\nMean residual (prediction minus label): smiling faces {final['smile>0.5']['mean_residual_pred_minus_label']:+.3f}, "
      f"others {final['smile<=0.5']['mean_residual_pred_minus_label']:+.3f}. "
      f"Prediction std {final['prediction_std']:.3f} vs label std {final['label_std']:.3f} (predictions are shrunk toward the mean).\n")
    w(f"ONNX export: onnxruntime (Python) vs PyTorch on 200 test images, max abs diff {onnx['max_abs_diff']:.2e}, "
      f"mean {onnx['mean_abs_diff']:.2e}.\n")

    w("## Phase 4: browser verification (Playwright, headless Chromium, real app)\n")
    w("### 1. End to end accuracy\n")
    w(f"300 SCUT test images (seeded random sample) fed as PNG files through the app's `Scorer.process` "
      f"(decode, MediaPipe Face Landmarker, alignment, ONNX Runtime Web).\n")
    w("| Metric | Value |\n|---|---|")
    w(f"| Pearson, browser | {f(e['pearson_js'])} |")
    w(f"| Pearson, Python reference, same 300 images | {f(same)} |")
    w(f"| Pearson, Python, same images without alignment | {f(e['pearson_python_unaligned_same_images'])} |")
    w(f"| MAE, browser | {f(e['mae_js'])} |")
    w(f"| Browser vs Python raw score, mean / max abs diff | {e['js_vs_python_abs_diff_mean']:.2e} / {e['js_vs_python_abs_diff_max']:.2e} |")
    w(f"| Eye centers, browser vs Python MediaPipe, mean / max px diff | {e['eye_center_px_diff_mean']:.4f} / {e['eye_center_px_diff_max']:.4f} |")
    w(f"| Time per photo (headless Chromium, 1 thread) | {e['ms_per_image_mean']:.0f} ms |")
    t = res["tensor_parity"]
    w(f"| Preprocessing parity, 20 images: JS tensor vs Python tensor | max abs diff {t['tensor_max_abs_diff']}, {t['tensor_values_differing']} values differ |")
    w(f"| ONNX Runtime Web vs onnxruntime Python on identical tensors | max abs diff {t['onnx_web_vs_python_ort_max_abs_diff']:.2e} |")
    w("")
    w("### 2. Determinism\n")
    w(f"Same image scored 20 times in one page: {d['unique_outputs']} unique float32 output "
      f"(raw {d['raw']:.6f}, bits 0x{d['float32_bits_hex']}). In a fresh browser context: identical = {d['fresh_context_identical']}.\n")
    w("### 3. Robustness to JPEG re-encoding (50 test images)\n")
    w("| Quality | Mean abs change | Max abs change | Mean signed change |\n|---|---|---|---|")
    for k, v in res["jpeg"].items():
        w(f"| {k[1:]} | {v['mean_abs_change']:.4f} | {v['max_abs_change']:.4f} | {v['mean_signed_change']:+.4f} |")
    w("\nChanges are in raw points (1 to 5 scale); 0.4 is the \"photos disagree\" threshold.\n")
    w("### 4. Quality gates\n")
    w("| Fixture | Expected | Got | Pass |\n|---|---|---|---|")
    for k, v in q.items():
        exp = v["spec"].get("expect_status") or (", ".join(v["spec"].get("expect", [])) or "no flags")
        got = v["status"] if v["status"] != "ok" else ("; ".join(v["flags"]) or "no flags")
        if k == "exif_rot6":
            got += f" (raw diff vs upright copy {v['abs_diff_vs_upright']:.4f})"
        if k == "big":
            got += f" (raw diff vs Python {v['abs_diff_vs_python']:.4f}, vs the original 350 px image {v['abs_diff_vs_original_350']:.4f})"
        w(f"| {k} | {exp} | {got} | {'yes' if v['pass'] else 'NO'} |")
    w("\n`rotated30`: a SCUT face rotated 30 degrees in plane. `turned`: the SCUT test face with the largest yaw. "
      "`smiling`: the SCUT test face with the highest smile score. `two_faces`: two SCUT faces side by side. "
      "`exif_rot6`: pixels stored sideways with EXIF orientation 6, must score like the upright copy. "
      "`big`: the neutral face upscaled 4x inside a 3000x2200 frame (exercises the antialiased pre-shrink); "
      "must match the Python reference within 0.01.\n")
    w("### 5. Mobile layout\n")
    w(f"Viewport 390x844 (DPR 2, touch), four photos added through the real file input. Document scrollWidth "
      f"{m['scrollWidth']} for innerWidth {m['innerWidth']}; elements outside the viewport: {len(m['offenders'])}. "
      f"Screenshots: `tests/out/mobile_390x844.png`, `tests/out/mobile_390_full.png` (copied to `docs/`).\n")
    w(f"Result card shown: PSL {m['ui']['psl']}, 1 to 10 {m['ui']['ten']}, raw {m['ui']['raw']}, percentile {m['ui']['pct']} "
      f"({m['ui']['meta']}). Re-adding the same file: seen before = {m['seen_before']['seen']}, identical score = {m['seen_before']['same']}.\n")
    open(os.path.join(ROOT, "VALIDATION.md"), "w").write("\n".join(L) + "\n")
    print("wrote VALIDATION.md")


if __name__ == "__main__":
    main()
